name: RookisCustomEnchantments
version: '${project.version}'
main: world.lemmy.rookiscustomenchantments.RookisCustomEnchantments
api-version: '1.20'
commands:
  redeem-event:
    description: Get the Enchantment
    usage: /<command>
